### ISSUE TITLE
Is it possible to release the model trained on Pix3D?

### ISSUE THREAD

**Issue by ZezhouCheng** [hzxie/Pix2Vox#20]
Dear authors, it would be nice to see how the SOTA model performs on real images. Is it possible to release the model trained on Pix3D?

**Comment by hzxie** [comment]
We didn't release the pretrained model on Pix3D because it was trained on a dataset generated by ourselves (with the RenderForCNN pipeline).
We want to release the pretrained model and the generated dataset at the same time for reproducibility.
However, both the generated dataset and pretrained models were lost due to disk damage.
