### ISSUE TITLE
Why does the reconstructed 3D volumes have the same orientation?

### ISSUE THREAD

**Issue by rkchamp25** [hzxie/Pix2Vox#54]
How all the produced 3d coarse volumes have the same orientation even though the images are of different views and which part of the code is responsible for this? 
![image](https://user-images.githubusercontent.com/43476979/99874604-5957f400-2c0f-11eb-9782-67e9521b3d60.png)

**Comment by hzxie** [comment]
Actually, this is an "object-centered" reconstruction method. (As discussed in [Shin et al., CVPR 2018](https://openaccess.thecvf.com/content_cvpr_2018/html/Shin_Pixels_Voxels_and_CVPR_2018_paper.html))
For different views, the reconstructed object have the same orientation because the GTs for them are the same.
